//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprey.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Poprey.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By purchasing, you agree with .
        /// </summary>
        public static string Bag_FooterTermsAndConditions {
            get {
                return ResourceManager.GetString("Bag_FooterTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rules.
        /// </summary>
        public static string Bag_FooterTermsAndConditionsUnderlined {
            get {
                return ResourceManager.GetString("Bag_FooterTermsAndConditionsUnderlined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay By Card.
        /// </summary>
        public static string Bag_PayByCard {
            get {
                return ResourceManager.GetString("Bag_PayByCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string Bag_PayPal {
            get {
                return ResourceManager.GetString("Bag_PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string Bag_TotalPrice {
            get {
                return ResourceManager.GetString("Bag_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string Bag_Wallet {
            get {
                return ResourceManager.GetString("Bag_Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your E-mail
        ///to order.
        /// </summary>
        public static string Email_Header {
            get {
                return ResourceManager.GetString("Email_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email_Hint {
            get {
                return ResourceManager.GetString("Email_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By purchasing, you agree with the rules.
        /// </summary>
        public static string Email_License {
            get {
                return ResourceManager.GetString("Email_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add account.
        /// </summary>
        public static string FailedToAddAccount {
            get {
                return ResourceManager.GetString("FailedToAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar hashtags not found.
        /// </summary>
        public static string Hashtag_SimilarHashtagsNotFound {
            get {
                return ResourceManager.GetString("Hashtag_SimilarHashtagsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashtag.
        /// </summary>
        public static string HashtagHeader {
            get {
                return ResourceManager.GetString("HashtagHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hashtag.
        /// </summary>
        public static string HashtagPlaceholder {
            get {
                return ResourceManager.GetString("HashtagPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already saved.
        /// </summary>
        public static string Instagram_AccountAlreadySaved {
            get {
                return ResourceManager.GetString("Instagram_AccountAlreadySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit of {0} saved accounts reached. Please remove on of the existing ones..
        /// </summary>
        public static string Instagram_AccountLimitReached {
            get {
                return ResourceManager.GetString("Instagram_AccountLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string Instagram_AddComment {
            get {
                return ResourceManager.GetString("Instagram_AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Likes.
        /// </summary>
        public static string Instagram_Auto {
            get {
                return ResourceManager.GetString("Instagram_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, there is no such profile yet or it is closed. Please check login and availablity of your account.
        /// </summary>
        public static string Instagram_ClosedOrDoesNotExistError {
            get {
                return ResourceManager.GetString("Instagram_ClosedOrDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Instagram_Comments {
            get {
                return ResourceManager.GetString("Instagram_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Instagram_Custom {
            get {
                return ResourceManager.GetString("Instagram_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string Instagram_Followers {
            get {
                return ResourceManager.GetString("Instagram_Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For new posts.
        /// </summary>
        public static string Instagram_ForNewPosts {
            get {
                return ResourceManager.GetString("Instagram_ForNewPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get 10 Free.
        /// </summary>
        public static string Instagram_GetTenFree {
            get {
                return ResourceManager.GetString("Instagram_GetTenFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradual.
        /// </summary>
        public static string Instagram_Gradual {
            get {
                return ResourceManager.GetString("Instagram_Gradual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant.
        /// </summary>
        public static string Instagram_Instant {
            get {
                return ResourceManager.GetString("Instagram_Instant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Delivery.
        /// </summary>
        public static string Instagram_InstantDelivery {
            get {
                return ResourceManager.GetString("Instagram_InstantDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Start.
        /// </summary>
        public static string Instagram_InstantStart {
            get {
                return ResourceManager.GetString("Instagram_InstantStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Instagram_Like {
            get {
                return ResourceManager.GetString("Instagram_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This profile has no posts yet.
        /// </summary>
        public static string Instagram_NoPostsError {
            get {
                return ResourceManager.GetString("Instagram_NoPostsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Instagram_Normal {
            get {
                return ResourceManager.GetString("Instagram_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal looking.
        /// </summary>
        public static string Instagram_NormalLooking {
            get {
                return ResourceManager.GetString("Instagram_NormalLooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perma-
        ///    Snent.
        /// </summary>
        public static string Instagram_Permanent {
            get {
                return ResourceManager.GetString("Instagram_Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per post.
        /// </summary>
        public static string Instagram_Perpost {
            get {
                return ResourceManager.GetString("Instagram_Perpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string Instagram_Premium {
            get {
                return ResourceManager.GetString("Instagram_Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Instagram_Random {
            get {
                return ResourceManager.GetString("Instagram_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Looking.
        /// </summary>
        public static string Instagram_RealLooking {
            get {
                return ResourceManager.GetString("Instagram_RealLooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string Instagram_ShowMorePhotos {
            get {
                return ResourceManager.GetString("Instagram_ShowMorePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Instagram_Subscription {
            get {
                return ResourceManager.GetString("Instagram_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Instagram_Views {
            get {
                return ResourceManager.GetString("Instagram_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string InstagramHeader {
            get {
                return ResourceManager.GetString("InstagramHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string InstagramPlaceholder {
            get {
                return ResourceManager.GetString("InstagramPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connected.
        /// </summary>
        public static string InternetConnected {
            get {
                return ResourceManager.GetString("InternetConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet disconnected.
        /// </summary>
        public static string InternetDisconnected {
            get {
                return ResourceManager.GetString("InternetDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string MenuContactUs {
            get {
                return ResourceManager.GetString("MenuContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string MenuFaq {
            get {
                return ResourceManager.GetString("MenuFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string MenuPrivacyPolicy {
            get {
                return ResourceManager.GetString("MenuPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string MenuTermsOfService {
            get {
                return ResourceManager.GetString("MenuTermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit site.
        /// </summary>
        public static string MenuVisitSite {
            get {
                return ResourceManager.GetString("MenuVisitSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprey.
        /// </summary>
        public static string Poprey {
            get {
                return ResourceManager.GetString("Poprey", resourceCulture);
            }
        }
    }
}
